/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sessions.notavailable;

import com.project.frames.Lecturer_view;
import com.project.frames.WorkingDays_new;
import com.project.frames.mainframe;
import com.project.s2.DisplayStudentsTimetable;
import com.project.s2.GenarateTimeTableStructure;
import com.project.s2.ViewSessions;
import com.project.util.dbdetail;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author OSHANI
 */
public class notViewSession extends javax.swing.JFrame {
    private static Connection con;
    private PreparedStatement ps1;
    private PreparedStatement ps2;
    private PreparedStatement ps3;
    private PreparedStatement ps5;
    private PreparedStatement ps9;
    /**
     * Creates new form notViewSession
     */
    public notViewSession() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        //DISPLAY SESSIONS
        show_sessions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        session_view_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddSession = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        C_ID = new javax.swing.JComboBox();
        R_ID = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loc_id = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        session_view_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SESSION", "STATUS", "NOTAVAILABLE"
            }
        ));
        session_view_table.setRowHeight(130);
        session_view_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                session_view_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(session_view_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 2, 500, 490));

        jLabel1.setText("YOU HAVE SELECTED SESSION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 54, 188, 28));

        SID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(SID, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 54, 193, 28));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 488, -1, -1));

        AddSession.setBackground(new java.awt.Color(102, 0, 255));
        AddSession.setForeground(new java.awt.Color(255, 255, 255));
        AddSession.setText("Add Session");
        AddSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSessionActionPerformed(evt);
            }
        });
        jPanel1.add(AddSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 307, 277, -1));

        jLabel4.setText("ADD DATE COLUMN ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 138, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Time Table creation");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setText("ADD RAW ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 235, 128, -1));

        C_ID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mon", "tue", "wed", "thur", "fri", "sat", "sun" }));
        C_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_IDActionPerformed(evt);
            }
        });
        jPanel1.add(C_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 135, 200, -1));
        jPanel1.add(R_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 232, 145, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Make Sure Raw ID is belong to session, students");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 182, -1, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setText("Main Menu");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 270, 24));

        jLabel2.setText("Add Location ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 258, 107, 31));
        jPanel1.add(loc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 263, 145, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("View Created Students Tables ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 400, 277, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Genarate Time Table Structure ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 429, 277, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 920, 500));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Not Available Sessions");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/images/l1.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(jLabel11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int studentId(int id){
        int student_id=-89;
        try {
            
            con = dbdetail.getCon();
            
            ps5 = con.prepareStatement("select s_grp from sessions where id =?");
            ps5.setInt(1, id);
            ResultSet rs2 = ps5.executeQuery();
            String student_grp="";
            while (rs2.next()) {
                
                student_grp=rs2.getString(1);
                
                
               
                
            }
            
            
            ps9 = con.prepareStatement("select stuid from students where grpid =?");
            ps9.setString(1, student_grp);
           
            ResultSet rs7 = ps9.executeQuery();
            
            while (rs7.next()) {
                
                student_id =rs7.getInt(1);
                
                
               
                
            }
            
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(notViewSession.class.getName()).log(Level.SEVERE, null, ex);
        }
        return student_id;     
    }
    
    private void session_view_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_session_view_tableMouseClicked
        // TODO add your handling code here:
        int i=session_view_table.getSelectedRow();
        TableModel model=session_view_table.getModel();

        String id=model.getValueAt(i,0).toString();
        int session_id=Integer.parseInt(id);
        String notav=model.getValueAt(i, 3).toString();
        //String[] arrLec = notav.split(",");
        //String checkNotA=model.getValueAt(i, ICONIFIED)

        try{
            if(!notav.equalsIgnoreCase("NotAvailable")){
                JOptionPane.showMessageDialog(null,"This is not a not available session or already added.Select diffrerent session");
            }
            else{
                int y=Integer.parseInt(id);

                int k_id=studentId(y);
                JOptionPane.showMessageDialog(null, "You Have Selected Session:"+y+"  Student group ID:"+k_id);
                SID.setText(id);
                 //String[] check =myMethod(session_id);
                   //System.out.println("wwwwwww"+check[0]+"oooo"+check[1]);
                   //mon time
                   
                   
            }
        }catch(Exception e){}

    }//GEN-LAST:event_session_view_tableMouseClicked
    private String[] myMethod(int id){
    
        String[] arr=new String[2];
        
        try {
            
            con = dbdetail.getCon();
            
            ps5 = con.prepareStatement("select day,time from notAvailable where sessionid =?");
            ps5.setInt(1, id);
            ResultSet rs2 = ps5.executeQuery();
            
            while (rs2.next()) {
                
                arr[0]=rs2.getString(1);
                arr[1]=String.valueOf(rs2.getFloat(2));
                
               
                
            }
            
             con.close();
        } catch (SQLException ex) {
            Logger.getLogger(notViewSession.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return arr; 
    }
    private void AddSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSessionActionPerformed
        //Calling the main method
        int y=calledByAddSessions();
        if(y==-45){}
        else if(y==-29){
            JOptionPane.showMessageDialog(null, "This time slot and day is marked as Not Available");
        }
        else if(y==-89){
            JOptionPane.showMessageDialog(null, "All the lectuers ,that belong to this sessions tables have not created yet.Please create it and try again.");
        }
        else if(y==-77){
            JOptionPane.showMessageDialog(null, "Students table has not created yet.Please create it and try again.");
        }else if(y==-79){
            JOptionPane.showMessageDialog(null, "Location table has not created yet.Please create it and try again.");
        }
        else if(y==-34){
            JOptionPane.showMessageDialog(null, "location and students time slots are not matching");
        }else if(y==-64){
            JOptionPane.showMessageDialog(null, "lectuers and students time slots are not matching");
        }else if(y==-900){
            JOptionPane.showMessageDialog(null, "Not enough time slots for the duration in students time table or Your Raw ID is not belong to the selected student grp");
        }else if(y==-800){
            JOptionPane.showMessageDialog(null, "Not enough time slots for the duration in location time table");
        }else if(y==-880){
            JOptionPane.showMessageDialog(null, "Not enough time slots for the duration in some lectuers time table");
        }

        notViewSession ob4=new notViewSession();
        ob4.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_AddSessionActionPerformed

    private int findLecId(String name){
        int lec_id=-89;
        try {
            
            con = dbdetail.getCon();
            
            ps5 = con.prepareStatement("select id from lec where name =?");
            ps5.setString(1, name);
            ResultSet rs2 = ps5.executeQuery();
            
            while (rs2.next()) {
                
                lec_id=rs2.getInt(1);
            
            }
            
             con.close();
        } catch (SQLException ex) {
            Logger.getLogger(notViewSession.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lec_id;     
    }
    
    private void show_sessions(){
    DefaultTableModel model1 =(DefaultTableModel)session_view_table.getModel();
    
        /*model1.setColumnIdentifiers(new Object[] {
                "Column 1", "Column 2", "Column 3" });

        JTable table = new JTable(model1);
        table.setRowHeight(300);*/
        Object[] row=new Object[10];
        
        ArrayList<com.project.model.Session> ar= getsessions();
        
        for(Object x:ar){
            com.project.model.Session object=new com.project.model.Session();
            object = (com.project.model.Session) x;
            
        row[0]=object.getId();    
        //lec,tag,s_grp,sub_grp,subject_c,no_students,duration
        String sess="<html>"+"<br>"+object.getLec()+"<br>"+object.getTag()+"<br>"+object.getS_grp()+"<br>"+object.getSub_grp()+"<br>"+object.getSubject_c()+"<br>"+"No of Students"+object.getN0_students()+"<br>"+"Duration"+object.getDuration()+"<br>"+"</html>";
        row[1]=sess;
        row[2]=object.getStatus();
        row[3]=object.getnotAvailable();
       
        model1.addRow(row);
        }
}
    
    private ArrayList getsessions(){
     ArrayList arr=new ArrayList();
        try {
           
            
            con = dbdetail.getCon();
            ps1 = con.prepareStatement("select id,lec,tag,s_grp,sub_grp,subject_c,no_students,duration,status,notavailable from sessions");
            ResultSet rs12 = ps1.executeQuery();
            
            while (rs12.next()) {
                //name+emmid+faculty+department+center+building+level+rank123
                com.project.model.Session ar=new com.project.model.Session();
                ar.setId(rs12.getInt(1));
                ar.setLec(rs12.getString(2));
                ar.setTag(rs12.getString(3));
                ar.setS_grp(rs12.getString(4));
                ar.setSub_grp(rs12.getString(5));
                ar.setSubject_c(rs12.getString(6));
                ar.setN0_students(rs12.getInt(7));
                ar.setDuration(rs12.getInt(8));
                ar.setStatus(rs12.getString(9));
                ar.setnotAvailable(rs12.getString(10));
                arr.add(ar);
                
            }
            
           
        } catch (SQLException ex) {
            Logger.getLogger(ViewSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
    return arr;
}
    
    private void C_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_IDActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        mainframe ob=new mainframe();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DisplayStudentsTimetable ob6=new DisplayStudentsTimetable();
        ob6.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        GenarateTimeTableStructure ob9=new GenarateTimeTableStructure();
        ob9.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

   private int calledByAddSessions(){
    try{
        
            
        String hh=loc_id.getText();
        //getting location id by input
        int locationID=Integer.parseInt(hh);
        //getting session id by input
        int sessionID=Integer.parseInt(SID.getText());
        
        
        
       
        com.project.model.Session ob=new com.project.model.Session();
        ob=getOneDetailSession(sessionID);
        
        int duration=ob.getDuration();
        
        //lectuer handling
        String lec=ob.getLec();
        String[] arrLec = lec.split(",");
        
        int lec_count = arrLec.length;
        int[] lecArr=new int[lec_count];
        
        int lec_cc=-1;
        for(String jj:arrLec){
        // System.out.println("spliit array"+jj);
            int xxx = findLecId(jj);
            //System.out.println("lec id******************"+xxx);
            lec_cc++;
            lecArr[lec_cc]=xxx;
            
        //lecArr.add();
        }
        //getting the lecturer tables has created
        for(int i=0;i<=lec_cc;i++){
            int lec_yy=findLectuersHasCreatedTheTable(lecArr[i]);
            if(lec_yy==-1){
             return -89;
            }
            
        }
        
        
        //getting the student group by
        int sudentgroupID=getOneDetaillStudent(ob.getS_grp());
        //checking if the time table created
        int yy=findStudentHasCreatedTheTable(sudentgroupID);
        if(yy==-1){
            return -77;
        }
        int locyy=findLocationHasCreatedTheTable(locationID);
        if(locyy==-1){
            return -79;
        }
        JOptionPane.showMessageDialog(null, "Checking Whether all the time table has created, is succedded.Other parts are proceeding");
        //System.out.println("group idddddddd"+sudentgroupID);
        
        ///***************************************************************************************************
        //ADDING DETAILS FIRSTLY IN STUDENT TIME TABLE
        
        //getting the input data for raw id and column id by that user inserted.
        String columnId=(String) C_ID.getSelectedItem();
        int rawid=(int) R_ID.getValue();
        
        /*float tts=getTime(rawid);
        String[] check =myMethod(sessionID);
        float rr=Float.parseFloat(check[1]);
        
        if((columnId.equalsIgnoreCase(check[0]) && (tts == rr) )){
            return -29;
        }*/
        
        //getting the details(session) that need to store in time table 
        String ll=gettinnglocationName(locationID);
        String sessionDeatils="<html>"+ob.getLec()+"<br>"+ob.getS_grp()+"<br>"+ob.getSub_grp()+"<br>"+ob.getSubject_c()+"<br>"+ob.getTag()+"<br>"+ll+"<br>"+"----Not Available----"+"</html>";
        
        //getting the table format(1 hour or 30 min) and timslot
        float[] checkts= getTimeSlots(rawid);
        
        float timeslott=checkts[1];
        //System.out.println("displaying time sloooots"+timeslott);
        
        //checking wheather room tt has the same time slot and timeslot type
        //JOptionPane.showMessageDialog(null, timeslott);
        float[] checks_location=getTimeSlotsLoc(timeslott,locationID);
        //checking lectuers also have the same time slot and timeslot type
        //returning if not available time slots
        if(checks_location[0]==-100){
         return -34;
        }
        
        //This time slot and day is marked as Not Available
        float tts=getTime(rawid);
        String[] check =myMethod(sessionID);
        float rr=Float.parseFloat(check[1]);
        
        if((columnId.equalsIgnoreCase(check[0]) && (tts == rr) )){
            return -29;
        }
        
        //all the lec checking process.
        
        for(int j=0;j<=lec_cc;j++){
            float[] checks_lec = getTimeSlotsLectueres(timeslott,lecArr[j]);
            if(checks_lec[0]==-500){
            return -64;
            }
            
            if(checks_lec[0]==-1){
        
            for(int y=0;y<duration;y++){
            int no1=(int) (y+checks_lec[1]);    
            String rrr = checkIfLec(no1,columnId,locationID,sessionDeatils,lecArr[j]);    
            System.out.println("checkfree  "+y+rrr);
            if(!rrr.equalsIgnoreCase("Yes")){
               //int s=Integer.parseInt("ttt");
                return -880;
            }
            
            }
            
        
        }else{
            for(int y=0;y<duration*2;y++){
             int no2=(int) (y+checks_lec[1]);    
             String rrr1 = checkIfLec(no2,columnId,locationID,sessionDeatils,lecArr[j]);        
             System.out.println("checkfree  "+y+"*******"+rrr1);
             if(!rrr1.equalsIgnoreCase("Yes")){
               //int s=Integer.parseInt("ttt");
                 return -880;
            }
            }
            
        }
            
            
        }
        
       JOptionPane.showMessageDialog(null, "Checking Whether all lectuers tables have, all the time slots available, is succedded.Other parts are proceeding");
        
        //checking whether the students,locations,lectuers slots are available else add
        
        //checking students
        if(checkts[0]==-1){
        
            for(int y=0;y<duration;y++){
            String rrr=checkIfFree(y+rawid,columnId,locationID,sessionDeatils,sudentgroupID);    
            System.out.println("checkfree  "+y+rrr);
            if(!rrr.equalsIgnoreCase("Yes")){
               //int s=Integer.parseInt("ttt");
                return -900;
            }
            
            }
            
        
        }else{
            for(int y=0;y<duration*2;y++){
             String rrr1=checkIfFree(y+rawid,columnId,locationID,sessionDeatils,sudentgroupID);        
             System.out.println("checkfree  "+y+"*******"+rrr1);
             if(!rrr1.equalsIgnoreCase("Yes")){
               //int s=Integer.parseInt("ttt");
                 return -900;
            }
            }
            
             }
        JOptionPane.showMessageDialog(null, "Checking Whether students table has all the time slots available, is succedded.Other parts are proceeding");
        //checking locations
         if(checks_location[0]==-1){
        
            for(int y=0;y<duration;y++){
            int no1=(int) (y+checks_location[1]);    
            String rrr = checkIfFreeLocation(no1,columnId,locationID,sessionDeatils,locationID);    
            System.out.println("checkfree  "+y+rrr);
            if(!rrr.equalsIgnoreCase("Yes")){
               //int s=Integer.parseInt("ttt");
                return -800;
            }
            
            }
            
        
        }else{
            for(int y=0;y<duration*2;y++){
             int no2=(int) (y+checks_location[1]);    
             String rrr1 = checkIfFreeLocation(no2,columnId,locationID,sessionDeatils,locationID);        
             System.out.println("checkfree  "+y+"*******"+rrr1);
             if(!rrr1.equalsIgnoreCase("Yes")){
               //int s=Integer.parseInt("ttt");
                 return -800;
            }
            }
            
        }
        JOptionPane.showMessageDialog(null, "Checking Whether location table has all the time slots available, is succedded.Other parts are proceeding");
        //Need to add after all checking students,locations,lecturers
        //After checking adding students
        if(checkts[0]==-1){
        
            
            for(int y=0;y<duration;y++){
            
            AddSeesionstott(y+rawid,columnId,locationID,sessionDeatils,sudentgroupID);
            }
        
        }else{
            
            for(int y=0;y<duration*2;y++){
            
            AddSeesionstott(y+rawid,columnId,locationID,sessionDeatils,sudentgroupID);
            }
  
        }
        JOptionPane.showMessageDialog(null, "Students time table is Updated.Other parts are proceeding");
        //Addning locations
        if(checks_location[0]==-1){
            for(int y=0;y<duration;y++){
            int no1=(int) (y+checks_location[1]);
            AddSeesionstottLocation(no1,columnId,locationID,sessionDeatils,locationID);
            }
        
        }else{
            
            
            for(int y=0;y<duration*2;y++){
            int no2=(int) (y+checks_location[1]);
            AddSeesionstottLocation(no2,columnId,locationID,sessionDeatils,locationID);
            }
            
        
        
        }
         JOptionPane.showMessageDialog(null, "Locations time table is Updated.Other things are proceeding");
         //Adding Lectuers
        for(int j=0;j<=lec_cc;j++){
            float[] checks_lec = getTimeSlotsLectueres(timeslott,lecArr[j]);
            if(checks_lec[0]==-1){
            for(int y=0;y<duration;y++){
            int no1=(int) (y+checks_lec[1]);
            AddSeesionstottLect(no1,columnId,locationID,sessionDeatils,lecArr[j]);
            }
        
        }else{
            
            
            for(int y=0;y<duration*2;y++){
            int no2=(int) (y+checks_lec[1]);
            AddSeesionstottLect(no2,columnId,locationID,sessionDeatils,lecArr[j]);
            }
            
        
        
        }
        
        
        }
         JOptionPane.showMessageDialog(null, "All lectuers  time tables are Updated.");
        }catch(Exception e){
        
        }
        
    return 0;
    }
   private float getTime(int rid){
       float timeslot=0;
   try {
            
             con = dbdetail.getCon();
             
             ps5 = con.prepareStatement("select timeslot from stu_timetable where id =?");
             ps5.setInt(1, rid);
             ResultSet rs2 = ps5.executeQuery();
             
             while (rs2.next()) {
                 
                 timeslot=rs2.getFloat(1);
                
                 
                 
                 
             }
             
             con.close();
             
             
             
            
         } catch (SQLException ex) {
             Logger.getLogger(GenarateTimeTableStructure.class.getName()).log(Level.SEVERE, null, ex);
         }
        
         return timeslot; 
   
   
   }
     private String gettinnglocationName(int id){
     try {
             String x;
             
             con = dbdetail.getCon();
             
             ps5 = con.prepareStatement("select name from room where id =?");
             ps5.setInt(1, id);
             ResultSet rs2 = ps5.executeQuery();
             
             while (rs2.next()) {
                 
                 x=rs2.getString(1);
                
                 
                 return x;
                 
             }
             
             con.close();
             
             
             
            
         } catch (SQLException ex) {
             Logger.getLogger(GenarateTimeTableStructure.class.getName()).log(Level.SEVERE, null, ex);
         }
        
         return "notfound"; 
    }
    private float[] getTimeSlotsLoc(float timeslott,int locationID){
       // JOptionPane.showMessageDialog(null, "INSIDE getTimeSlotLoc");
        int k1=-78;
        float k2=0;
        float re[]=new float[2];
    try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select id from room_timetable where roomid=? and timeslot=?");
             ps2.setInt(1, locationID);
             ps2.setFloat(2, timeslott);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 //JOptionPane.showMessageDialog(null, "INSIDE getTimeSlotLoc 1st while loop");
              k1=rs11.getInt(1);
              re[1]=k1;
                
            }
             if(k1==-78){
                 re[0]=-100;
             return re;
             }
             ps3 = con.prepareStatement("select timeslot from stu_timetable where id=?");
             ps3.setInt(1,k1+1);
            ResultSet rs12 = ps3.executeQuery();
             while (rs12.next()) {
                 
              k2=rs12.getFloat(1);
               
                
            }
            
            re[0]=timeslott-k2;
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println("checking time slottttt"+re);
        return re;
        
    
    } 
    private float[] getTimeSlotsLectueres(float timeslott,int lecID){
       // JOptionPane.showMessageDialog(null, "INSIDE getTimeSlotLoc");
        int k1=-78;
        float k2=0;
        float re[]=new float[2];
    try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select id from lec_timetable where lecid=? and timeslot=?");
             ps2.setInt(1, lecID);
             ps2.setFloat(2, timeslott);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 //JOptionPane.showMessageDialog(null, "INSIDE getTimeSlotLoc 1st while loop");
              k1=rs11.getInt(1);
              re[1]=k1;
                
            }
             if(k1==-78){
                 re[0]=-500;
             return re;
             }
             ps3 = con.prepareStatement("select timeslot from lec_timetable where id=?");
             ps3.setInt(1,k1+1);
            ResultSet rs12 = ps3.executeQuery();
             while (rs12.next()) {
                 
              k2=rs12.getFloat(1);
               
                
            }
            
            re[0]=timeslott-k2;
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println("checking time slottttt"+re);
        return re;
        
    
    }
    /*public static float round(float d, int decimalPlace) {
    BigDecimal bd = new BigDecimal(Float.toString(d));
    bd = bd.setScale(decimalPlace, BigDecimal.ROUND_HALF_UP);
    return bd.floatValue();
    }*/
    
    private float[] getTimeSlots(int id){
        float k1=0;
        float k2=0;
        float[] re=new float[2];
    try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select timeslot from stu_timetable where id=?");
             ps2.setInt(1, id);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 
              k1=rs11.getFloat(1);
              
              //JOptionPane.showMessageDialog(null, k1);
              
              re[1]=k1; 
                
            }
             
             ps3 = con.prepareStatement("select timeslot from stu_timetable where id=?");
             ps3.setInt(1, id+1);
            ResultSet rs12 = ps3.executeQuery();
             while (rs12.next()) {
                 
              k2=rs12.getFloat(1);
               
                
            }
            
            re[0]=k1-k2;
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println("checking time slottttt"+re);
        return re;
        
    
    }
    private void UpdateSession(){
         try {
             int id=Integer.parseInt(SID.getText());
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("UPDATE sessions set notavailable='NotAvailable_Added' where id=?");
             ps2.setInt(1, id);
            ps2.execute();
             
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    private void AddSeesionstott(int rid,String cid,int loc,String session,int stuid){

        /*
        sql = "UPDATE diseaseinfo"
      + " SET `" + colname + "` = ?"
      + " WHERE companyname = 'mycom' AND diseaseName = ?";
        
        preparedStmt.setString(1, attrData);
        preparedStmt.setString(2, medname);
        */
         try {
                       String  sql = "UPDATE stu_timetable"
                        + " SET `" + cid + "` = ?"
                        + " WHERE id = ? AND stuid=?";
                        con = dbdetail.getCon();
                        
                        //ps3 = con.prepareStatement("UPDATE stu_timetable SET mon=?,tue=? where id=? ");
                        ps3 = con.prepareStatement(sql);
                        ps3.setString(1,session);
                        ps3.setInt(2,rid);
                        ps3.setInt(3,stuid);
                        
                        
                        
                       
                        ps3.execute();
                        //System.out.println("hello");
                        UpdateSession();
        
            con.setAutoCommit(false);
            con.close();
         } catch (Exception ex) {
             
             Logger.getLogger(WorkingDays_new.class.getName()).log(Level.SEVERE, null, ex);
         
         }
   
    
    }
    private void AddSeesionstottLocation(int rid,String cid,int loc,String session,int locId){

       
         try {
                       String  sql = "UPDATE room_timetable"
                        + " SET `" + cid + "` = ?"
                        + " WHERE id = ? AND roomid=?";
                        con = dbdetail.getCon();
                        
                        //ps3 = con.prepareStatement("UPDATE stu_timetable SET mon=?,tue=? where id=? ");
                        ps3 = con.prepareStatement(sql);
                        ps3.setString(1,session);
                        ps3.setInt(2,rid);
                        ps3.setInt(3,locId);
                        
                        
                        
                       
                        ps3.execute();
                        //System.out.println("hello");
                        UpdateSession();
            con.setAutoCommit(false);
            con.close();
         } catch (Exception ex) {
             
             Logger.getLogger(WorkingDays_new.class.getName()).log(Level.SEVERE, null, ex);
         
         }
   
    
    }
    private void AddSeesionstottLect(int rid,String cid,int loc,String session,int locId){

       
         try {
                       String  sql = "UPDATE lec_timetable"
                        + " SET `" + cid + "` = ?"
                        + " WHERE id = ? AND lecid=?";
                        con = dbdetail.getCon();
                        
                        //ps3 = con.prepareStatement("UPDATE stu_timetable SET mon=?,tue=? where id=? ");
                        ps3 = con.prepareStatement(sql);
                        ps3.setString(1,session);
                        ps3.setInt(2,rid);
                        ps3.setInt(3,locId);
                        
                        
                        
                       
                        ps3.execute();
                        //System.out.println("hello");
                        UpdateSession();
            con.setAutoCommit(false);
            con.close();
         } catch (Exception ex) {
             
             Logger.getLogger(WorkingDays_new.class.getName()).log(Level.SEVERE, null, ex);
         
         }
   
    
    }
    private String checkIfFree(int rid,String cid,int loc,String session,int stuid){
            String ret="";
            int k=0;
        /*
        sql = "UPDATE diseaseinfo"
      + " SET `" + colname + "` = ?"
      + " WHERE companyname = 'mycom' AND diseaseName = ?";
        
        preparedStmt.setString(1, attrData);
        preparedStmt.setString(2, medname);
        */
         try {
                      /* String  sql = "SELECT"+cid+"From  stu_timetable"
                        + " WHERE id = ? AND stuid=?";
                        con = dbdetail.getCon();*/
                        
                        //ps3 = con.prepareStatement("UPDATE stu_timetable SET mon=?,tue=? where id=? ");
                        con = dbdetail.getCon();
                        ps3 = con.prepareStatement("select mon,tue,wed,thur,fri,sat,sun from stu_timetable where id = ? AND stuid=?");
                        ps3.setInt(1,rid);
                        ps3.setInt(2,stuid);
                        
                        if(cid.equals("mon")){
                        k=1;
                        }else if(cid.equals("tue")){
                        k=2;
                        }else if(cid.equals("wed")){
                        k=3;
                        }else if(cid.equals("thur")){
                        k=4;
                        }else if(cid.equals("fri")){
                        k=5;
                        }else if(cid.equals("sat")){
                        k=6;
                        }else if(cid.equals("sun")){
                        k=7;
                        }
                        
                        ResultSet rs11 = ps3.executeQuery();
                        while (rs11.next()) {
                 
                        ret=rs11.getString(k);
                        
                
                        }
                        
                        
                        
        
            con.setAutoCommit(false);
            con.close();
         } catch (Exception ex) {
             
             Logger.getLogger(WorkingDays_new.class.getName()).log(Level.SEVERE, null, ex);
         
         }
    return ret;
    
    }
    private String checkIfFreeLocation(int rid,String cid,int loc,String session,int stuid){
            String ret="";
            int k=0;
      
         try {
                       con = dbdetail.getCon();
                        ps3 = con.prepareStatement("select mon,tue,wed,thur,fri,sat,sun from room_timetable where id = ? AND roomid=?");
                        ps3.setInt(1,rid);
                        ps3.setInt(2,stuid);
                        
                        if(cid.equals("mon")){
                        k=1;
                        }else if(cid.equals("tue")){
                        k=2;
                        }else if(cid.equals("wed")){
                        k=3;
                        }else if(cid.equals("thur")){
                        k=4;
                        }else if(cid.equals("fri")){
                        k=5;
                        }else if(cid.equals("sat")){
                        k=6;
                        }else if(cid.equals("sun")){
                        k=7;
                        }
                        
                        ResultSet rs11 = ps3.executeQuery();
                        while (rs11.next()) {
                 
                        ret=rs11.getString(k);
                        
                
                        }
                        
                        
                        
        
            con.setAutoCommit(false);
            con.close();
         } catch (Exception ex) {
             
             Logger.getLogger(WorkingDays_new.class.getName()).log(Level.SEVERE, null, ex);
         
         }
    return ret;
    
    }
    private String checkIfLec(int rid,String cid,int loc,String session,int stuid){
            String ret="";
            int k=0;
      
         try {
                       con = dbdetail.getCon();
                        ps3 = con.prepareStatement("select mon,tue,wed,thur,fri,sat,sun from lec_timetable where id = ? AND lecid=?");
                        ps3.setInt(1,rid);
                        ps3.setInt(2,stuid);
                        
                        if(cid.equals("mon")){
                        k=1;
                        }else if(cid.equals("tue")){
                        k=2;
                        }else if(cid.equals("wed")){
                        k=3;
                        }else if(cid.equals("thur")){
                        k=4;
                        }else if(cid.equals("fri")){
                        k=5;
                        }else if(cid.equals("sat")){
                        k=6;
                        }else if(cid.equals("sun")){
                        k=7;
                        }
                        
                        ResultSet rs11 = ps3.executeQuery();
                        while (rs11.next()) {
                 
                        ret=rs11.getString(k);
                        
                
                        }
                        
                        
                        
        
            con.setAutoCommit(false);
            con.close();
         } catch (Exception ex) {
             
             Logger.getLogger(WorkingDays_new.class.getName()).log(Level.SEVERE, null, ex);
         
         }
    return ret;
    
    }
    private int getOneDetaillStudent(String name){
        
        try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select stuid from students where grpid=?");
             ps2.setString(1, name);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 
              int k=rs11.getInt(1);
               return k;
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        return -1;
    } 
    private com.project.model.Session getOneDetailSession(int id){
        com.project.model.Session ar=new com.project.model.Session();
        try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select id,lec,tag,s_grp,sub_grp,subject_c,no_students,duration,status,notavailable from sessions where id=?");
             ps2.setInt(1, id);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 
                ar.setId(rs11.getInt(1));
                ar.setLec(rs11.getString(2));
                 ar.setTag(rs11.getString(3));
                ar.setS_grp(rs11.getString(4));
                ar.setSub_grp(rs11.getString(5));
                ar.setSubject_c(rs11.getString(6));
                ar.setN0_students(rs11.getInt(7));
                ar.setDuration(rs11.getInt(8));
                ar.setStatus(rs11.getString(9));
                ar.setnotAvailable(rs11.getString(10));
               
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ar;
    }
    private int findStudentHasCreatedTheTable(int id){
        
        try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select * from stu_timetable where stuid=?");
             ps2.setInt(1, id);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 
              
               return 890;
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        return -1;
    } 
    private int findLocationHasCreatedTheTable(int id){
        
        try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select * from room_timetable where roomid=?");
             ps2.setInt(1, id);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 
              
               return 890;
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        return -1;
    } 
    private int findLectuersHasCreatedTheTable(int id){
        
        try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select * from lec_timetable where lecid=?");
             ps2.setInt(1, id);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 
              
               return 890;
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        return -1;
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notViewSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSession;
    private javax.swing.JComboBox C_ID;
    private javax.swing.JSpinner R_ID;
    private javax.swing.JLabel SID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loc_id;
    private javax.swing.JTable session_view_table;
    // End of variables declaration//GEN-END:variables
}
