/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.sessions;

import com.project.frames.AddConsecutive;
import com.project.frames.Lecturer_view;
import com.project.frames.LocationHome;
import com.project.frames.Statistics;
import com.project.frames.Subject;
import com.project.frames.WorkingDays_new;
import com.project.frames.lecturers;
import com.project.frames.mainframe;
import com.project.parallelSession.ParallelSession;
import com.project.s2.ViewSessions;
import com.project.util.dbdetail;
import com.tag.all.ViewEditDeleteTag;
import com.project.model.Session;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author OSHANI
 */
public class ConsecutiveSession extends javax.swing.JFrame {
    Connection con = null;
    
    PreparedStatement ps = null;
    PreparedStatement ps11;
    PreparedStatement ps12;
    PreparedStatement ps1;
    PreparedStatement ps2;
    PreparedStatement ps9;
    /**
     * Creates new form ConsecutiveSession
     */
    public ConsecutiveSession() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        displayId();
        
        //Database Connection
        con = (Connection) dbdetail.getCon();
        
        ArrayList arr2 = getId_t();
        for(Object x:arr2){
          ts.addItem((String) x);
          }
        
        ArrayList arr4 = getId_L();
        for(Object y:arr4){
          ls.addItem((String) y);
          }
    }

    private ArrayList getId_t(){
        
        ArrayList arr=new ArrayList();
         try {
             
             
             con = dbdetail.getCon();
             
             
             ps11 = con.prepareStatement("select id from sessions where status='Normal' OR status='Normal_Sub_Grp'");
             
             ResultSet rs11 = ps11.executeQuery();
             
             while (rs11.next()) {
                 
                 arr.add(rs11.getString(1));
                 
             }
         } catch (SQLException ex) {
             Logger.getLogger(ConsecutiveSession.class.getName()).log(Level.SEVERE, null, ex);
         }
          return arr;  
    
    }
    
    private ArrayList getId_L(){
        
        ArrayList arr=new ArrayList();
         try {
             
             
             con = dbdetail.getCon();
             
             
             ps11 = con.prepareStatement("select id from sessions where status='Normal' OR status='Normal_Sub_Grp'");
             
             ResultSet rs11 = ps11.executeQuery();
             
             while (rs11.next()) {
                 
                 arr.add(rs11.getString(1));
                 
             }
         } catch (SQLException ex) {
             Logger.getLogger(ConsecutiveSession.class.getName()).log(Level.SEVERE, null, ex);
         }
          return arr;  
    
    }
    
    private int displayId(){
         con = dbdetail.getCon();
         try {
             ps12= con.prepareStatement("select cid from consecutive where cid >= all (select cid from consecutive)");
             ResultSet rs12 = ps12.executeQuery();
             int x=0;
            while (rs12.next()) {
                
                x=rs12.getInt(1);
                x++;
                
                
            }
            String y=String.valueOf(x);
            cid.setText(y);
            
            return x;
         } catch (SQLException ex) {
             Logger.getLogger(ConsecutiveSession.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
           
           return -99; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ts = new javax.swing.JComboBox<>();
        ls = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cid = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        main = new javax.swing.JButton();
        parallel = new javax.swing.JButton();
        notoverlap = new javax.swing.JButton();
        consecutive = new javax.swing.JButton();
        viewLectures2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/images/l1.PNG"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setText("Consecutive Sessions");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Session ID 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Session ID 2");

        Add.setBackground(new java.awt.Color(102, 0, 255));
        Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/images/add.jpg"))); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ID");

        view.setBackground(new java.awt.Color(102, 0, 255));
        view.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/images/view.png"))); // NOI18N
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ts, 0, 244, Short.MAX_VALUE)
                    .addComponent(ls, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 660, 560));

        jPanel12.setBackground(new java.awt.Color(102, 0, 102));

        main.setBackground(new java.awt.Color(204, 204, 255));
        main.setText("Main Menu");
        main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });

        parallel.setBackground(new java.awt.Color(102, 0, 102));
        parallel.setForeground(new java.awt.Color(255, 255, 255));
        parallel.setText("Parallel Session");
        parallel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        parallel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parallelActionPerformed(evt);
            }
        });

        notoverlap.setBackground(new java.awt.Color(102, 0, 102));
        notoverlap.setForeground(new java.awt.Color(255, 255, 255));
        notoverlap.setText("Not Overlap Session");
        notoverlap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        notoverlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notoverlapActionPerformed(evt);
            }
        });

        consecutive.setBackground(new java.awt.Color(102, 0, 102));
        consecutive.setForeground(new java.awt.Color(255, 255, 255));
        consecutive.setText("Consecutive Session");
        consecutive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        consecutive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consecutiveActionPerformed(evt);
            }
        });

        viewLectures2.setBackground(new java.awt.Color(102, 0, 102));
        viewLectures2.setForeground(new java.awt.Color(255, 255, 255));
        viewLectures2.setText("View Session IDs");
        viewLectures2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLectures2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parallel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notoverlap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consecutive, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(viewLectures2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consecutive, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parallel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notoverlap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewLectures2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        int no=callAddConsecutiveSessions();
        if(no==-56){
        JOptionPane.showMessageDialog(null, "Please select different Sessions.");
        }else if(no==-34){
            JOptionPane.showMessageDialog(null, "Selected sessions cannot add as consecutive sessions.Select valid tag session");
        }
        else if(no==-99){
        JOptionPane.showMessageDialog(null, "Selected sessions cannot add as consecutive sessions.Sudents group need to be same.");
        }
    }//GEN-LAST:event_AddActionPerformed

    private Session getOneDetailSession(int id){
        Session ar=new Session();
        try {
           con = dbdetail.getCon();
            ps2 = con.prepareStatement("select id,lec,tag,s_grp,sub_grp,subject_c,no_students,duration,status from sessions where id=?");
            ps2.setInt(1, id);
            ResultSet rs11 = ps2.executeQuery();
             while (rs11.next()) {
                 
                ar.setId(rs11.getInt(1));
                ar.setLec(rs11.getString(2));
                ar.setTag(rs11.getString(3));
                ar.setS_grp(rs11.getString(4));
                ar.setSub_grp(rs11.getString(5));
                ar.setSubject_c(rs11.getString(6));
                ar.setN0_students(rs11.getInt(7));
                ar.setDuration(rs11.getInt(8));
                ar.setStatus(rs11.getString(9));
                
               
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer_view.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ar;
    }
    
    private int callAddConsecutiveSessions(){
        try{
            
        String n1=(String) ts.getSelectedItem();
        int n2=Integer.parseInt(n1);
        String c1=(String) ls.getSelectedItem();
        int c2=Integer.parseInt(c1);
        
        Session ob33= getOneDetailSession(n2);
        String s4=ob33.getS_grp();
        String s9=ob33.getTag();

        
        Session ob45= getOneDetailSession(c2);
        String s5=ob45.getS_grp();
        String s10=ob45.getTag();
    
         
        if(n2==c2){
           // JOptionPane.showMessageDialog(null, "Please select different Sessions.");
           // int yyy=Integer.parseInt("sd");
            return -56;
        }else if(s9.equals(s10)){
        //JOptionPane.showMessageDialog(null, "2 sessions durations are not same.");
            return -34;
        }
        else
        if(!s4.equals(s5)){
       
        // JOptionPane.showMessageDialog(null, "Selected sessions cannot add as consecutive.");
        // int xxx=Integer.parseInt("sd");
            return -99;
        }
        
        int x=0;
        
            ps9 = con.prepareStatement("select cid from consecutive where cid >= all (select cid from consecutive)");

            ResultSet rs1 = ps9.executeQuery();

            while (rs1.next()) {

                x=rs1.getInt(1);
                x++;

            }

            String q = "INSERT INTO consecutive (cid,sid1,sid2) values (?,?,?)";
            ps = con.prepareStatement(q);
            ps.setInt(1, x);
            ps.setString(2,n1);
            ps.setString(3,c1);

            ps.execute();

            JOptionPane.showMessageDialog(null, "successfully created consecutive session");
<<<<<<< HEAD
            AddConsecutive ob4=new  AddConsecutive();
=======
            ParallelSession ob4=new  ParallelSession();
>>>>>>> c03a2a05c407dc5b4ef7b45784f9c325737f4842
            ob4.setVisible(true);
            this.setVisible(false);
            
            UpdateSessions();

        }  catch (Exception ex) {
            //Logger.getLogger(ParallelSession.class.getName()).log(Level.SEVERE, null, ex);
             //JOptionPane.showMessageDialog(null, "Selected sessions cannot add as consecutive.Sudents group need to be same.");
        }
        return 0;
    }
    private void UpdateSessions(){
        String n1=(String) ts.getSelectedItem();
            int n2=Integer.parseInt(n1);
            String c1=(String) ls.getSelectedItem();
             int c2=Integer.parseInt(c1); 
        try {
            
       
            con = (Connection) dbdetail.getCon();
            ps9 = con.prepareStatement("UPDATE sessions SET status=?  WHERE id=? ");
            ps9.setString(1,"consecutive");
            ps9.setInt(2,n2);
            //ps1.setString(2,idd);

            ps9.execute();
            //JOptionPane.showMessageDialog(null, "View Consecutive Session");

            /*ViewSessions add=new  ViewSessions();
            this.setVisible(false);
            add.setVisible(true);*/

        } catch (SQLException ex) {
            //Logger.getLogger(ViewSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
             
            con = (Connection) dbdetail.getCon();
            ps9 = con.prepareStatement("UPDATE sessions SET status=?  WHERE id=? ");
            ps9.setString(1,"consecutive");
            ps9.setInt(2,c2);
            //ps1.setString(2,idd);

            ps9.execute();
            JOptionPane.showMessageDialog(null, "View Consecutive Session");

<<<<<<< HEAD
            AddConsecutive add=new  AddConsecutive();
=======
            ViewSessions add=new  ViewSessions();
>>>>>>> c03a2a05c407dc5b4ef7b45784f9c325737f4842
            this.setVisible(false);
            add.setVisible(true);

        } catch (SQLException ex) {
<<<<<<< HEAD
            Logger.getLogger(AddConsecutive.class.getName()).log(Level.SEVERE, null, ex);
=======
            Logger.getLogger(ViewSessions.class.getName()).log(Level.SEVERE, null, ex);
>>>>>>> c03a2a05c407dc5b4ef7b45784f9c325737f4842
        }
    }
        
        
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
            AddConsecutive add=new  AddConsecutive();
            this.setVisible(false);
            add.setVisible(true);
    }//GEN-LAST:event_viewActionPerformed

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        mainframe ob=new mainframe();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainActionPerformed

    private void parallelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parallelActionPerformed
        ParallelSession p=new ParallelSession();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_parallelActionPerformed

    private void notoverlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notoverlapActionPerformed
        NOTOVERLAPSESSION b=new NOTOVERLAPSESSION();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_notoverlapActionPerformed

    private void consecutiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consecutiveActionPerformed
        ConsecutiveSession a=new ConsecutiveSession();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consecutiveActionPerformed

    private void viewLectures2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLectures2ActionPerformed
        ViewSessions ob=new ViewSessions();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewLectures2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsecutiveSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsecutiveSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsecutiveSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsecutiveSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsecutiveSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel cid;
    private javax.swing.JButton consecutive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> ls;
    private javax.swing.JButton main;
    private javax.swing.JButton notoverlap;
    private javax.swing.JButton parallel;
    private javax.swing.JComboBox<String> ts;
    private javax.swing.JButton view;
    private javax.swing.JButton viewLectures2;
    // End of variables declaration//GEN-END:variables
}
